# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from transformers import AutoConfig

from xcai.basics import *
from xcai.maggi.utils import *
from xcai.models.nvembed.NVM0XX import NVM009, NVM0XXConfig

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ['WANDB_PROJECT'] = 'maggi_00-msmarco-00'

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str)
    parser.add_argument('--idx', type=int, required=True)
    parser.add_argument('--parts', type=int, required=True)

    parser.add_argument('--dset_type', type=str, default="beir")
    parser.add_argument('--save_suffix', type=str, default=None)

    parser.add_argument('--get_lbl_repr', action='store_true')
    parser.add_argument('--get_phr_repr', action='store_true')
    parser.add_argument('--get_tst_repr', action='store_true')
    parser.add_argument('--get_trn_repr', action='store_true')

    parser.add_argument('--batch_size', type=int, default=32)

    return parser.parse_known_args()[0]

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    input_args = parse_args()

    # output_dir = "/home/sasokan/suchith/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001"
    output_dir = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001"

    save_dir = f"{output_dir}/representations/{input_args.dset_type}/{input_args.dataset}/"
    data_dir = f"/data/datasets/{input_args.dset_type}/{input_args.dataset.replace('/', '-')}/XC/"

    token_dir = f"{output_dir}/tokenized_inputs/{input_args.dset_type}/{input_args.dataset.replace('/', '-')}"
    os.makedirs(token_dir, exist_ok=True)

    instruction = "/home/sasokan/suchith/xcai/xcai/models/nvembed/instructions.json"
    input_args.save_suffix = None 

    # instruction = "/home/sasokan/suchith/xcai/xcai/models/nvembed/instructions.json"
    # input_args.save_suffix = "phrase-aug-random"

    # instruction = "Given a multi-hop question, retrieve phrases relevant to the question"
    # input_args.save_suffix = "phrase-lbl"

    mname = 'nvidia/NV-Embed-v2'

    lbl_suffix = f"_{input_args.idx:02d}-{input_args.parts:02d}" if input_args.parts > 1 else ""
    if input_args.save_suffix is not None:
        qry_suffix = f"_{input_args.save_suffix}{lbl_suffix}" if len(lbl_suffix) else f"_{input_args.save_suffix}"
    else:
        qry_suffix = lbl_suffix

    if input_args.get_lbl_repr:
        fname = f"{token_dir}/label{lbl_suffix}.joblib"
        if os.path.exists(fname):
            dataset = joblib.load(fname)
        else:
            lbl_info_file = f"{data_dir}/raw_data/label.raw.csv"
            dataset = tokenized_labels(lbl_info_file, input_args.idx, input_args.parts, model_name=mname)
            joblib.dump(dataset, fname)

    elif input_args.get_phr_repr:
        fname = f"{token_dir}/phrase{lbl_suffix}.joblib"
        if os.path.exists(fname):
            dataset = joblib.load(fname)
        else:
            lbl_info_file = f"{data_dir}/raw_data/phrase.raw.csv"
            dataset = tokenized_labels(lbl_info_file, input_args.idx, input_args.parts, model_name=mname, max_length=64)
            joblib.dump(dataset, fname)

    elif input_args.get_tst_repr:
        fname = f"{token_dir}/test{qry_suffix}.joblib"
        if os.path.exists(fname):
            dataset = joblib.load(fname)
        else:
            qry_info_file = f"{data_dir}/raw_data/test.raw.csv"
            # qry_info_file = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001/raw_data/multihop/musique/test_phrase_topk-random.raw.txt"
            dataset = tokenized_query(qry_info_file, input_args.idx, input_args.parts, instruction, input_args.dataset, 
				      model_name=mname)
            joblib.dump(dataset, fname)

    elif input_args.get_trn_repr:
        fname = f"{token_dir}/train{qry_suffix}.joblib"
        if os.path.exists(fname):
            dataset = joblib.load(fname)
        else:
            qry_info_file = f"{data_dir}/raw_data/train.raw.csv"
            dataset = tokenized_query(qry_info_file, input_args.idx, input_args.parts, instruction, input_args.dataset,
				      model_name=mname)
            joblib.dump(dataset, fname)
    else:
        raise ValueError("Please pass flag to process the type of document.")

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=input_args.batch_size,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = NVM0XXConfig(
        margin=0.3,
        tau=0.1,
        n_negatives=10,
        normalize=False,
        apply_softmax=True,
        use_encoder_parallel=True,
    )
    hf_config = AutoConfig.from_pretrained(mname)
    for k in hf_config: setattr(config, k, getattr(hf_config, k))

    # Load model

    def model_fn(mname):
        model = NVM009.from_pretrained(mname, config=config)
        return model

    model = load_model(args.output_dir, model_fn, {"mname": mname}, do_inference=True, 
                       use_pretrained=True)

    # Learner

    learn = XCLearner(
        model=model,
        args=args,
        eval_dataset=dataset,
        data_collator=identity_collate_fn,
    )

    os.makedirs(save_dir, exist_ok=True)

    if input_args.get_lbl_repr: 
        get_and_save_representation(learn, dataset, f'{save_dir}/lbl_repr{lbl_suffix}.pth')

    elif input_args.get_phr_repr: 
        get_and_save_representation(learn, dataset, f'{save_dir}/phr_repr{lbl_suffix}.pth')

    elif input_args.get_tst_repr: 
        get_and_save_representation(learn, dataset, f'{save_dir}/tst_repr{qry_suffix}.pth')

    elif input_args.get_trn_repr: 
        get_and_save_representation(learn, dataset, f'{save_dir}/trn_repr{qry_suffix}.pth')


