# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ngame-for-msmarco-inference.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 3
import argparse, json, os
from tqdm.auto import tqdm

from transformers import AutoConfig

from xcai.misc import *
from xcai.main import *
from xcai.basics import *

from xcai.multihop import *
from xcai.models.nvembed.NVM0XX import NVM009, NVM0XXConfig

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 5
os.environ["WANDB_PROJECT"] = "04_musique"

def additional_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dset_type', type=str, default="multihop")
    parser.add_argument('--save_suffix', type=str, default=None)
    return parser.parse_known_args()[0]

# %% ../nbs/00_ngame-for-msmarco-inference.ipynb 20
if __name__ == '__main__':
    input_args = parse_args()
    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/data/suchith/datasets/processed/"

    extra_args = additional_args()
    extra_args.pct = 1.0

    output_dir = "/data/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001/"

    lbl_file = f"{output_dir}/representations/{extra_args.dset_type}/{input_args.dataset}/lbl_repr.pth"

    metric_dir = f"{output_dir}/metrics/{extra_args.dset_type}"
    suffix = "" if extra_args.save_suffix is None else f"_{extra_args.save_suffix}"

    mname = 'nvidia/NV-Embed-v2'

    config_file = "/home/sasokan/b-sprabhu/datasets/multihop/musique/XC/configs/data.json"

    train_dset, test_dset = load_linker_block("musique", config_file, input_args, extra_args)

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=800,
        per_device_eval_batch_size=1,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,
        warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-4,

        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,

        metric_for_best_model='N@10',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',

        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,

        label_names=["data_input_text"],
        use_saved_representation_for_indexing=True,
        label_representation_for_indexing_file=lbl_file,
    )

    config = NVM0XXConfig(
        margin=0.3,
        tau=0.1,
        n_negatives=10,
        normalize=False,
        apply_softmax=True,
        use_encoder_parallel=True,
    )
    hf_config = AutoConfig.from_pretrained(mname)
    for k in hf_config: setattr(config, k, getattr(hf_config, k))

    def model_fn(mname, config):
        model = NVM009.from_pretrained(mname, config=config)
        return model

    do_inference = check_inference_mode(input_args)
    model = load_model(args.output_dir, model_fn, {"mname": mname, "config": config}, do_inference=do_inference,
                       use_pretrained=input_args.use_pretrained)

    metric = PrecReclHits(test_dset.data.n_lbl, test_dset.data.data_lbl_filterer, prop=None if train_dset is None else train_dset.data.data_lbl,
                          pk=10, rk=200, hk=10, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200], rep_hk=[1, 3, 5, 10])

    learn = MultihopLearner(
        tokenizer=config_file,
        model=model,
        args=args,
        train_dataset=train_dset,
        eval_dataset=test_dset,
        data_collator=identity_collate_fn,
        compute_metrics=metric,
    )

    metrics = learn.evaluate(beam_size=10, num_hops=4, topk_per_hop=10)

    # Save metrics

    if metrics is not None:
        os.makedirs(metric_dir, exist_ok=True)
        metric_file = f"{metric_dir}/{input_args.dataset}{suffix}_multihop.json"
        with open(metric_file, "w") as file:
            json.dump(metrics, file, indent=4)

        print(metrics)


