# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np
import scipy.sparse as sp, argparse, math, torch.nn.functional as F

from typing import Optional
from tqdm.auto import tqdm

from transformers import AutoConfig

from xcai.basics import *
from xcai.maggi.utils import *
from xcai.models.nvembed.NVM0XX import NVM009, NVM0XXConfig, BidirectionalMistralConfig

from sugar.core import load_raw_file

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ['WANDB_PROJECT'] = 'maggi_00-msmarco-00'


def load_config(mname:str, skip_layer_start:Optional[int]=None, num_layers_to_skip:Optional[int]=None):
    hf_config = AutoConfig.from_pretrained(mname)
    text_config = BidirectionalMistralConfig(
        skip_layer_start=skip_layer_start,
        num_layers_to_skip=num_layers_to_skip,
    )
    for k in hf_config.text_config: 
        if k != "skip_layer_start" and k != "skip_layer_end":
            setattr(text_config, k, getattr(hf_config.text_config, k))

    config = NVM0XXConfig(
        margin=0.3,
        tau=0.1,
        n_negatives=10,
        normalize=False,
        apply_softmax=True,
        use_encoder_parallel=True,
        text_config=text_config,
        latent_attention_config=hf_config.latent_attention_config,
    )

    for k in hf_config: 
        if k != "text_config" and k != "latent_attention_config":
            setattr(config, k, getattr(hf_config, k))
    return config


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str)
    parser.add_argument('--dset_type', type=str, default="beir")
    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--skip_layer_start', type=int, default=10)
    parser.add_argument('--num_layers_to_skip', type=int, default=10)
    return parser.parse_known_args()[0]


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':

    # Input arguements

    input_args = parse_args()

    skip_layer_end = input_args.skip_layer_start + input_args.num_layers_to_skip - 1
    expt_prefix = f"skip-layers-{input_args.skip_layer_start:02d}-{skip_layer_end:02d}"

    output_dir = "/data/suchith/outputs/maggi/01_nvembed-skip-layers-001"

    save_dir = f"{output_dir}/representations/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(save_dir, exist_ok=True)

    pred_dir = f"{output_dir}/predictions/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(pred_dir, exist_ok=True)

    data_dir = f"/data/datasets/{input_args.dset_type}/{input_args.dataset.replace('/', '-')}/XC/"
    instruct_file = "/home/sasokan/suchith/xcai/xcai/models/nvembed/instructions.json"
    gt_file = f"/data/datasets/{input_args.dset_type}/{input_args.dataset}/XC/tst_X_Y.npz"

    lbl_dir = f"/data/suchith/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001"
    lbl_file = f"{lbl_dir}/representations/{input_args.dset_type}/{input_args.dataset}/lbl_repr.pth"

    token_dir = f"{output_dir}/tokenized_inputs/{input_args.dset_type}/{input_args.dataset.replace('/', '-')}"
    os.makedirs(token_dir, exist_ok=True)

    metric_dir = f"{output_dir}/metrics/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(metric_dir, exist_ok=True)
    metric_file = f"{metric_dir}/{input_args.dataset}_{expt_prefix}.json"

    mname = 'nvidia/NV-Embed-v2'

    # Load tokens

    fname = f"{token_dir}/test.joblib"
    if os.path.exists(fname):
        dataset = joblib.load(fname)
    else:
        qry_info_file = f"{data_dir}/raw_data/test.raw.csv"
        dataset = tokenized_query(qry_info_file, 0, 1, instruct_file, input_args.dataset, 
                                  model_name=mname)
        joblib.dump(dataset, fname)

    # Training arguements

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=input_args.batch_size,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    # Load configuration

    config = load_config(mname, skip_layer_start=input_args.skip_layer_start, num_layers_to_skip=10)

    # Load model

    def model_fn(mname):
        model = NVM009.from_pretrained(mname, config=config)
        return model

    model = load_model(args.output_dir, model_fn, {"mname": mname}, do_inference=True, use_pretrained=True)

    learn = XCLearner(
        model=model,
        args=args,
        eval_dataset=dataset,
        data_collator=identity_collate_fn,
    )

    # Load representation

    tst_file = None # f'{save_dir}/tst_repr.pth')
    tst_repr = F.normalize(get_and_save_representation(learn, dataset, tst_file), dim=1)
    lbl_repr = F.normalize(torch.load(lbl_file), dim=1)

    # Compute metrics

    tst_lbl = sp.load_npz(gt_file)
    metrics, tst_pred = compute_metrics(tst_repr, tst_lbl, lbl_repr, metric_type="H")
    sp.save_npz(f"{pred_dir}/test_predictions_{expt_prefix}.npz", tst_pred)

    with open(metric_file, "w") as file:
        json.dump(metrics, file, indent=4)

    print(metrics)



