# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os, torch, json, torch.multiprocessing as mp, joblib, numpy as np
import scipy.sparse as sp, argparse, math, torch.nn.functional as F

from typing import Optional
from tqdm.auto import tqdm
from torch.utils.data import DataLoader

from transformers import AutoConfig

from xcai.basics import *
from xcai.metrics import ndcg
from xcai.maggi.utils import *
from xcai.models.nvembed.NVM0XX import NVM009, NVM0XXConfig, BidirectionalMistralConfig

from xclib.utils.sparse import retain_topk

from sugar.core import load_raw_file

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ['WANDB_PROJECT'] = 'maggi_00-msmarco-00'

def load_config(mname:str):
    hf_config = AutoConfig.from_pretrained(mname)
    config = NVM0XXConfig(
        margin=0.3,
        tau=0.1,
        n_negatives=10,
        normalize=False,
        apply_softmax=True,
        use_encoder_parallel=True,
    )
    for k in hf_config: setattr(config, k, getattr(hf_config, k))
    return config

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str)
    parser.add_argument('--dset_type', type=str, default="beir")
    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--skip_layer_start', type=int, default=None)
    parser.add_argument('--num_layers_to_skip', type=int, default=None)
    return parser.parse_known_args()[0]

def get_msmarco_per_instance_ndcg(fname):
    output_dir = "/data/suchith/outputs/maggi/00_nvembed-to-compute-msmarco-embeddings-001/"
    repr_dir = f"{output_dir}/representations/beir/msmarco/"

    lbl_repr = F.normalize(combine_embeddings(f"{repr_dir}/lbl_repr.pth", "lbl"), dim=1).T

    n_trn = 5000
    trn_repr = F.normalize(combine_embeddings(f"{repr_dir}/trn_repr.pth", "trn")[:n_trn], dim=1)
    trn_lbl = sp.load_npz(f"/data/datasets/{input_args.dset_type}/{input_args.dataset}/XC/trn_X_Y.npz")[:n_trn]

    metrics, trn_pred = compute_metrics(trn_repr, trn_lbl, lbl_repr, metric_type="M")
    metrics = ndcg(trn_pred, trn_lbl, k=10, per_instance=True)

    np.save(fname, metrics)

    return metrics

def load_data(idx, fname):
    data_lbl = sp.load_npz("/data/datasets/beir/msmarco/XC/cross_encoder/ce-positives-topk-05_trn_X_Y_top-5.npz")
    data_lbl = data_lbl[idx]

    _, data_info = load_raw_file("/home/sasokan/b-sprabhu/datasets/beir/msmarco/XC/raw_data/train.raw.txt")
    data_info = [data_info[i] for i in idx]

    _, lbl_info = load_raw_file("/home/sasokan/b-sprabhu/datasets/beir/msmarco/XC/raw_data/label.raw.txt")
    lbl_info = [lbl_info[i] for i in data_lbl.indices]
    
    data_meta = sp.load_npz("/data/datasets/beir/msmarco/XC/cross_encoder/ce-negatives-topk-05_trn_X_Y_remove-top-10.npz")
    data_meta = retain_topk(data_meta[idx], k=5)

    _, meta_info = load_raw_file("/home/sasokan/b-sprabhu/datasets/beir/msmarco/XC/raw_data/ce-scores.raw.txt")
    meta_info = [meta_info[i] for i in data_meta.indices]

    output = data_lbl, data_info, lbl_info, data_meta, meta_info
    joblib.dump(output, fname)

    return output

def get_representation(model, dataloader:DataLoader, representation_attribute:str, representation_accumulation_steps:Optional[int]=None, 
                       to_cpu:Optional[bool]=True):
    data_host, all_data = None, None
    
    for step, inputs in tqdm(enumerate(dataloader), total=len(dataloader)):
        inputs = {k: v.to(model.device) for k,v in inputs.items()}
        with torch.no_grad(): 
            with torch.amp.autocast(device_type="cuda"):
                o = model(**inputs, output_hidden_states=True)

                breakpoint()

            data = getattr(o, representation_attribute)

        if representation_accumulation_steps is not None and (step + 1) % representation_accumulation_steps == 0:
            pass

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':

    # Input arguements

    input_args = parse_args()
    input_args.dset_type, input_args.dataset = "beir", "msmarco"

    output_dir = "/data/suchith/outputs/maggi/02_nvembed-score-across-layers-001"

    state_dir = f"{output_dir}/hidden_states/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(state_dir, exist_ok=True)

    metric_dir = f"{output_dir}/metrics/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(metric_dir, exist_ok=True)

    data_dir = f"{output_dir}/data/{input_args.dset_type}/{input_args.dataset}/"
    os.makedirs(data_dir, exist_ok=True)

    instruct_file = "/home/sasokan/suchith/xcai/xcai/models/nvembed/instructions.json"

    mname = 'nvidia/NV-Embed-v2'

    # Load tokens

    ## queries to consider

    fname = f"{metric_dir}/trn_ndcg"
    metrics = np.load(fname + ".npy") if os.path.exists(fname + ".npy") else get_msmarco_per_instance_ndcg(fname)
    idx = np.argsort(metrics[:, -1])[::-1][:10]

    fname = f"{data_dir}/data.joblib"
    output = joblib.load(fname) if os.path.exists(fname) else load_data(idx, fname)
    data_lbl, data_info, lbl_info, data_meta, meta_info = output

    ## tokenization

    fname = f"{data_dir}/tokenized.joblib"
    if os.path.exists(fname):
        trn_dset, lbl_dset, neg_dset = joblib.load(fname)
    else:
        trn_dset = tokenized_query(data_info, 0, 1, instruct_file, "msmarco", model_name=mname)
        lbl_dset = tokenized_labels(lbl_info, 0, 1, model_name=mname)
        neg_dset = tokenized_labels(meta_info, 0, 1, model_name=mname)
        joblib.dump((trn_dset, lbl_dset, neg_dset), fname)

    # Training arguements

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=100,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    # Load configuration

    config = load_config(mname)

    # Load model

    def model_fn(mname):
        model = NVM009.from_pretrained(mname, config=config)
        return model

    model = load_model(args.output_dir, model_fn, {"mname": mname}, do_inference=True, use_pretrained=True)

    learn = XCLearner(
        model=model,
        args=args,
        eval_dataset=lbl_dset,
        data_collator=identity_collate_fn,
    )

    # Get representation here

    output = get_representation(model, lbl_dset, "data_output")

