# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/maggi',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/maggi',
                'lib_path': 'maggi'},
  'syms': {'maggi.core': {'maggi.core.foo': ('core.html#foo', 'maggi/core.py')}}}
